### ISSUE TITLE
Actions non eseguiti.

### ISSUE THREAD

**Issue by antoninoLorenzo** [JacopoPassariello/TuringCareers#20]
Abbiamo inserito la cartella del progetto in CoreSystem_TC/TuringCareers dove attualmente ci sono file come .gitignore (che viene ignorato essendoci l'altro .gitignore nel root) e la cartella .github/workflows. 
Bisogna capire se si può impostare una cartella per le actions oppure se bisogna spostare i workflows fuori da CoreSystem_TC/TuringCareers

**Comment by ClaudioGaudino** [comment]
https://docs.github.com/en/actions/quickstart
letteralmente la prima cosa che dice è di mettere la cartella .github/workflows nella root della repo

**Comment by antoninoLorenzo** [comment]
Ok, ma a quanto pare non ci avevo visto male, se spostiamo .github/workflows nel folder principale vengono eseguiti, ma se vedi il primo Action eseguito (attualmente l'unico) c'è un errore relativo al fatto che non trova il pom.xml nella cartella corrente.
Diciamo che il problema che abbiamo è relativo al setup dei package, in quanto nella repository github andrebbe il contenuto che attualmente sta sotto CoreSystemTC/TuringCareers.
La mia soluzione sarebbe spostare tutto nella cartella principale, però se riuscite a risolvere in un altro modo tanto di guadagnato.
